name: DAB and ACA Setup

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: 'cwiederspan/adventureworksdab'
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: azure/docker-login@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push
        run: |
          docker build ./dab -f ./dab/Dockerfile -t $IMAGE_NAME:${{ github.sha }} -t $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest

  provision:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy Bicep file
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: ${{ vars.BASE_NAME }}
          template: ./infra/main.bicep
          parameters: 'baseName=${{ vars.BASE_NAME}} location=${{ vars.LOCATION }} databaseName=${{ vars.SQL_DB_NAME }}'
          failOnStdErr: false